manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: d09087f4dc280b8fdb1d32d63b03cc10162b89ce  # main
      import: app/west.yml
  self:
    path: config
